name: Publish image

on:
  workflow_dispatch:
    inputs:
      image:
        description: "The OCI image name. This must not include a tag or digest."
        type: string
        default: "docker.io/70801476/oss-na24-slsa-workshop-project1-echo-server"
      digest:
        description: "The OCI image digest. The image digest of the form '<algorithm>:<digest>' (e.g. 'sha256:abcdef...')"
        type: string
        default: "sha256:docker.io/70801476/oss-na24-slsa-workshop-project1-echo-server@sha256:20d4e6391b1e139c08d91ca4fc3309f53156f376d90cbd6ad29ee69458b74c7f"
      environment:
        type: choice
        description: Environment to use
        options: 
        - prod
        - staging

permissions: read-all

defaults:
  run:
    shell: bash

env:
  IMAGE_REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}-echo-server

jobs:
  publish:
    permissions:
      id-token: write # for creating OIDC tokens for signing.
      packages: write # for uploading attestations.
      contents: read # To read the repo.
    uses: minatotakaaki/oss-na24-slsa-workshop-organization/.github/workflows/image-publisher.yml@main
    with:
      environment: ${{ inputs.environment }}
      image: ${{ inputs.image }}
      digest: ${{ inputs.digest }}
      # Use name rather than env variable because env are not available for reusable workflows.
      registry-username: 70801476
      #registry-username: ${{ github.actor }}
    secrets:
      registry-password: ${{ secrets.REGISTRY_PASSWORD }}
      #registry-password: ${{ secrets.GITHUB_TOKEN }}
